// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNiZXqhX6Avm-58ZnqrX391vUeQXvSuWE',
    appId: '1:161646519211:web:9fe5623a7f3dfd31b5a8ee',
    messagingSenderId: '161646519211',
    projectId: 'mynotes-ajit',
    authDomain: 'mynotes-ajit.firebaseapp.com',
    storageBucket: 'mynotes-ajit.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1KbDqclMD8rzK8OpWWaaXvXtFACbZJcM',
    appId: '1:161646519211:android:99323499db4e4d66b5a8ee',
    messagingSenderId: '161646519211',
    projectId: 'mynotes-ajit',
    storageBucket: 'mynotes-ajit.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzhcK3-JpFMNi_hJAicu26nu1kmT4a4fw',
    appId: '1:161646519211:ios:0946d628bef36c3ab5a8ee',
    messagingSenderId: '161646519211',
    projectId: 'mynotes-ajit',
    storageBucket: 'mynotes-ajit.appspot.com',
    iosClientId: '161646519211-3voffu9l58qd8mitga3u4tpgp2ag59bu.apps.googleusercontent.com',
    iosBundleId: 'com.test123.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzhcK3-JpFMNi_hJAicu26nu1kmT4a4fw',
    appId: '1:161646519211:ios:0946d628bef36c3ab5a8ee',
    messagingSenderId: '161646519211',
    projectId: 'mynotes-ajit',
    storageBucket: 'mynotes-ajit.appspot.com',
    iosClientId: '161646519211-3voffu9l58qd8mitga3u4tpgp2ag59bu.apps.googleusercontent.com',
    iosBundleId: 'com.test123.mynotes',
  );
}
